/**
 * A complete song: every synth parameter + all sequencer/drum banks +
 * both chain lanes. Portable as a JSON file and storable in localStorage
 * slots (mirrors the Presets pattern in `preset.ts`).
 */
import type { ParamBus } from './params';
import type { PatternStore, SeqStep, DrumCell, SamplerStep, MotionStep, MotionAssign, MotionTrack } from './patterns';
import { SEQ_LENGTH, DRUM_TRACK_COUNT, makeDrumBank, makeSeqBank, emptyPatternSnapshot } from './patterns';
import type { Arrangement } from '../audio/transport/arrangement';
import type { XyPadStore, XyAssign } from './xy-pad';
import { XY_DEFAULT_ASSIGN } from './xy-pad';
import { validateSongFile } from './song-validate';
import { isAuthorSong, expandAuthorSong } from './song-author';
import { compactSongForExport } from './serialize';
import { SlotStore } from './slot-store';
import { SONG_VERSION } from './song-version';
// Re-exported so the long-standing `import { SONG_VERSION } from './song'` keeps
// working; the constant itself lives in a pure module the MCP bundle can read.
export { SONG_VERSION } from './song-version';
// Generated by `npm run clean:demos`, guarded by `npm run check:demos`. Widened
// from the literal type TS infers for a JSON import — it is looked up by a
// filename computed at runtime, and an entry may legitimately be missing (a demo
// added without regenerating the index; JSON_DEMOS falls back to the filename).
import demoIndexJson from './demos-index.json';
const DEMO_INDEX = demoIndexJson as Record<string, string>;

const store = new SlotStore('websynth.song.');

export interface ChainData {
  enabled: boolean;
  steps: number[];
}

export interface SongFile {
  format: 'websynth-song';
  /** Hand-maintained alongside `SONG_VERSION` — TS cannot derive `1|…|N` from a
   *  number without recursive-type machinery this codebase doesn't use. */
  version: 1 | 2 | 3 | 4 | 5 | 6;
  name: string;
  params: Record<string, number>;
  /** v1-v5: one track per bank. Since v6 this is still **track 1** only —
   *  tracks 2-4 live in the additive `seqTracks` (sequencer.md REQ-13). */
  seqBanks: SeqStep[][];
  /**
   * v6 — `seqTracks[bank][track]`, indexed by the REAL track number, so index 0
   * is always null (track 1 is `seqBanks`). An empty track is null. Costs one
   * null per bank and removes the off-by-one an "extra tracks" array invites.
   */
  seqTracks?: (SeqStep[] | null)[][];
  drumBanks: DrumCell[][][];
  seqChain: ChainData;
  drumChain: ChainData;
  // ---- v2: sampler (optional so v1 files still load) ----
  samplerBanks?: SamplerStep[][][];
  samplerChain?: ChainData;
  /** Filenames only — decoded audio is not embedded; user reloads files. */
  sampleNames?: (string | null)[];
  // ---- v3: XY Pad axis assignment (optional so v1/v2 files still load) ----
  xy?: XyAssign;
  // ---- v4: motion sequencer (optional so v1-v3 files still load) ----
  motionBanks?: MotionStep[][];
  /** Per-bank axis override; null = inherit the song's XY Pad assignment. */
  motionAssigns?: (MotionAssign | null)[];
  motionChain?: ChainData;
  /** v5 — the two extra single-param motion tracks per bank. */
  motionTracks?: (MotionTrack | null)[][];
}

/**
 * The narrow sampler view `apply` needs to evict stale audio (song-mode.md
 * REQ-3b). Structural, so `state/` never imports the audio layer —
 * `SamplerMachine` satisfies it.
 */
export interface SamplerSlots {
  setBuffer(slot: number, buf: AudioBuffer | null): void;
}

/**
 * Split the store's 3-D seq banks into the v6 file shape: track 1 stays in
 * `seqBanks` (handled by the caller) and tracks 2-4 become `seqTracks`, with an
 * empty track written as null. When no extra track holds a step the key is
 * omitted entirely, so a one-track song serializes exactly as it did pre-v6.
 */
function splitSeqTracks(banks: SeqStep[][][]): { seqTracks?: (SeqStep[] | null)[][] } {
  const used = banks.some((bank) => bank.slice(1).some((row) => row.some((s) => s.on)));
  if (!used) return {};
  return {
    seqTracks: banks.map((bank) =>
      bank.map((row, t) => (t === 0 || !row.some((s) => s.on) ? null : row.map((s) => ({ ...s }))))),
  };
}

/** The inverse: rebuild `[bank][track][step]` for the store. Every version
 *  before 6 simply has no `seqTracks`, so its banks come back one-track. */
function mergeSeqTracks(file: SongFile): SeqStep[][][] {
  return file.seqBanks.map((track0, b) => {
    const bank = makeSeqBank();
    bank[0] = track0;
    const extra = file.seqTracks?.[b];
    if (extra) {
      for (let t = 1; t < bank.length; t++) {
        const row = extra[t];
        if (row) bank[t] = row;
      }
    }
    return bank;
  });
}

export const Song = {
  capture(bus: ParamBus, patterns: PatternStore, arr: Arrangement, name: string, xy?: XyPadStore): SongFile {
    const snap = patterns.snapshot();
    return {
      format: 'websynth-song',
      version: SONG_VERSION,
      name,
      params: bus.snapshot(),
      // Track 1 keeps the v1-v5 field; 2-4 ride in the additive one, omitted
      // entirely when empty so a one-track song is byte-identical to before.
      seqBanks: snap.seqBanks.map((bank) => bank[0]!.map((s) => ({ ...s }))),
      ...splitSeqTracks(snap.seqBanks),
      drumBanks: snap.drumBanks,
      seqChain: { enabled: arr.seq.enabled, steps: [...arr.seq.steps] },
      drumChain: { enabled: arr.drum.enabled, steps: [...arr.drum.steps] },
      samplerBanks: snap.samplerBanks,
      samplerChain: { enabled: arr.sampler.enabled, steps: [...arr.sampler.steps] },
      sampleNames: [...patterns.sampleNames],
      xy: xy ? xy.get() : { ...XY_DEFAULT_ASSIGN },
      motionBanks: snap.motionBanks,
      motionAssigns: snap.motionAssigns,
      motionTracks: snap.motionTracks,
      motionChain: { enabled: arr.motion.enabled, steps: [...arr.motion.steps] },
    };
  },

  apply(
    file: SongFile,
    bus: ParamBus,
    patterns: PatternStore,
    arr: Arrangement,
    xyStore?: XyPadStore,
    sampler?: SamplerSlots,
  ): void {
    bus.resetDefaults();      // authoritative: clear stale params before applying
    bus.restore(file.params);
    // A slot's decoded buffer belongs to the NAME beside it, so evict the audio
    // of every slot this file renames (song-mode.md REQ-3b) — otherwise the
    // previous song's sample keeps playing under the new song's label, with no
    // .needs-reload hint to betray it. Done BEFORE restore so the store's own
    // sample-meta emit repaints each slot against the settled buffers. A file
    // that OMITS sampleNames renames nothing, so the REQ-3 inherit exception
    // below still holds for v1 files.
    if (sampler && file.sampleNames) {
      for (let i = 0; i < patterns.sampleNames.length; i++) {
        if ((file.sampleNames[i] ?? null) !== (patterns.sampleNames[i] ?? null)) {
          sampler.setBuffer(i, null);
        }
      }
    }
    // Motion is authoritative: a file that omits a motion section has it BLANKED,
    // never inherited from the previously-loaded song (song-mode.md REQ-3,
    // motion-sequencer.md "Old songs load unchanged"). Without the `?? blank`
    // fallbacks, restore's skip-on-undefined leaves the prior song's anchors /
    // tracks live and still automating. Sampler banks/names are deliberately left
    // to inherit (see the v1-apply test): a file with no sampler section keeps the
    // user's loaded kit rather than orphaning it.
    const blank = emptyPatternSnapshot();
    patterns.restore({
      seqBanks: mergeSeqTracks(file),
      drumBanks: file.drumBanks,
      samplerBanks: file.samplerBanks,
      sampleNames: file.sampleNames,
      motionBanks: file.motionBanks ?? blank.motionBanks,
      motionAssigns: file.motionAssigns ?? blank.motionAssigns,
      motionTracks: file.motionTracks ?? blank.motionTracks,
    });
    arr.setSeqChain(file.seqChain?.steps ?? [0], file.seqChain?.enabled ?? false);
    arr.setDrumChain(file.drumChain?.steps ?? [0], file.drumChain?.enabled ?? false);
    arr.setSamplerChain(file.samplerChain?.steps ?? [0], file.samplerChain?.enabled ?? false);
    arr.setMotionChain(file.motionChain?.steps ?? [0], file.motionChain?.enabled ?? false);
    xyStore?.set(file.xy ?? XY_DEFAULT_ASSIGN);
  },

  /**
   * Serialize to the *canonical compact* form: numbers rounded to 4 significant
   * figures and step cells written default-sparse (`compactSongForExport`).
   * `saveSlot`/project zips/share links are whitespace-compact; `download` passes
   * `pretty` (matching `npm run clean:demos` byte-for-byte) so an exported file
   * dropped into `src/state/demos/` keeps readable git diffs.
   * `apply()`/`restore` re-expand the defaults on load — sound is unchanged.
   */
  toJSON(file: SongFile, pretty = false): string {
    return JSON.stringify(compactSongForExport(file), null, pretty ? 2 : undefined);
  },

  fromJSON(text: string): SongFile | null {
    const res = Song.parse(text);
    return res.ok ? res.file : null;
  },

  /** Like `fromJSON` but returns field-level errors instead of collapsing to null. */
  parse(text: string): import('./song-validate').SongValidation {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch (e) {
      return { ok: false, errors: ['File is not valid JSON: ' + (e as Error).message] };
    }
    // The compact authoring dialect expands to a canonical v3 file here, so
    // every ingest surface (Import, launchQueue, project zips, share links,
    // MCP) accepts it automatically. Input-only — see ADR-013.
    if (isAuthorSong(parsed)) return expandAuthorSong(parsed);
    return validateSongFile(parsed);
  },

  download(file: SongFile): void {
    const blob = new Blob([Song.toJSON(file, true) + '\n'], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${file.name.replace(/[^a-z0-9_-]+/gi, '_') || 'song'}.websynth.json`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  },

  readFile(f: File): Promise<SongFile | null> {
    return f.text().then((t) => Song.fromJSON(t));
  },

  /** Like `readFile` but returns field-level validation errors for the import UI. */
  parseFile(f: File): Promise<import('./song-validate').SongValidation> {
    return f.text().then((t) => Song.parse(t));
  },

  // ---- localStorage slots ----

  /**
   * Slot-picker contents: every JSON demo name (drop-in and built-in) plus the
   * user's stored slots, deduped and sorted. Drop-ins are listed even though
   * `loadSlot` cannot return them — they are fetched, not bundled (REQ-12) — so
   * the Song panel's Load button falls back to `loadDemo` for a name with no
   * stored slot. Zip demos stay out, as they always have: they are project
   * bundles, not song files.
   */
  list(): string[] {
    return [...new Set([
      ...JSON_DEMOS.map((d) => d.name),
      ...Object.keys(DEMO_SONGS),
      ...store.readIndex(),
    ])].sort();
  },

  saveSlot(name: string, file: SongFile): void {
    store.writeRaw(name, Song.toJSON(file));
    store.addToIndex(name);
  },

  /**
   * A stored slot, else a **built-in** demo. Stays synchronous and JSON-only, so
   * the fetched demos (drop-in JSON and zip alike) are not reachable here —
   * `SongPanel.loadDemo` is the door that knows about all three (REQ-12).
   */
  loadSlot(name: string): SongFile | null {
    const raw = store.readRaw(name);
    if (raw) return Song.fromJSON(raw);
    return DEMO_SONGS[name] ?? null;
  },

  deleteSlot(name: string): void {
    store.remove(name);
  },
};

/* ---------------- Demo songs ---------------- */

function baseParams(): Record<string, number> {
  const p: Record<string, number> = {
    'voicing.mode': 1,
    'osc1.wave': 2, 'osc1.octave': 0, 'osc1.detune': 0, 'osc1.level': 0.7,
    'osc2.wave': 2, 'osc2.octave': 0, 'osc2.detune': 7, 'osc2.level': 0.5,
    'sub.wave': 0, 'sub.octave': -1, 'sub.level': 0,
    'unison.voices': 1, 'unison.detune': 12,
    'analog.drift': 0,
    'mixer.noise': 0, 'mixer.glide': 0, 'glide.mode': 1,
    'filter.cutoff': 90, 'filter.resonance': 0.5, 'filter.drive': 1.2, 'filter.envAmount': 24,
    'env.amp.attack': 0.005, 'env.amp.decay': 0.2, 'env.amp.sustain': 0.8, 'env.amp.release': 0.4,
    'env.fil.attack': 0.005, 'env.fil.decay': 0.6, 'env.fil.sustain': 0.2, 'env.fil.release': 0.4,
    'lfo.rate': 4, 'lfo.amount': 0, 'lfo.wave': 0, 'lfo.dest': 0,
    'fx.dist.on': 0, 'fx.dist.drive': 0.3, 'fx.dist.tone': 3000, 'fx.dist.mix': 1,
    'fx.wah.on': 0, 'fx.phaser.on': 0,
    'fx.delay.on': 0, 'fx.delay.time': 0.35, 'fx.delay.feedback': 0.4, 'fx.delay.mix': 0.3,
    'fx.reverb.on': 0, 'fx.reverb.size': 0.6, 'fx.reverb.damp': 0.4, 'fx.reverb.mix': 0.25,
    'fx.djfilter': 0,
    'master.volume': 0.8, 'master.pitchBend': 0, 'master.modWheel': 0,
    'transport.bpm': 120,
    'arp.on': 0, 'seq.on': 1, 'drum.on': 1, 'drum.master': 0.9,
  };
  for (let i = 0; i < DRUM_TRACK_COUNT; i++) {
    p[`drum.t${i}.vol`] = 0.85;
    p[`drum.t${i}.tune`] = 0;
    p[`drum.t${i}.decay`] = 0.3;
    p[`drum.t${i}.mute`] = 0;
  }
  return p;
}

// NOTE: the seq helpers below deliberately do NOT share PatternStore's
// makeSeqBank() — they use different constants (fixed note 60, velocity 0.85 vs
// 60 + i%8 / 0.8), and those values are serialized into the committed demo
// songs and into share-link payloads. Unifying them would change demo bytes.
function seqFromNotes(notes: (number | null)[], gate = 0.5, velocity = 0.85): SeqStep[] {
  return Array.from({ length: SEQ_LENGTH }, (_, i) => {
    const n = notes[i] ?? null;
    return { on: n !== null, note: n ?? 60, velocity, gate, prob: 1, ratchet: 1, tie: false };
  });
}

function emptySeq(): SeqStep[] {
  return seqFromNotes(Array(SEQ_LENGTH).fill(null));
}

/** rows: map of track index → array of step indices that are ON. */
function drumFrom(rows: Record<number, number[]>): DrumCell[][] {
  const bank = makeDrumBank();
  for (const [t, steps] of Object.entries(rows)) {
    for (const s of steps) {
      const cell = bank[Number(t)]?.[s];
      if (cell) cell.on = true;
    }
  }
  return bank;
}

function pad4Seq(a: SeqStep[], b: SeqStep[]): SeqStep[][] {
  return [a, b, a.map((s) => ({ ...s })), a.map((s) => ({ ...s }))];
}
function pad4Drum(a: DrumCell[][], b: DrumCell[][]): DrumCell[][][] {
  const copy = (g: DrumCell[][]) => g.map((r) => r.map((c) => ({ ...c })));
  return [a, b, copy(a), copy(a)];
}

// --- Zombie Nation / Kernkraft 400: the 4-bar A-minor hook. 8th-note grid
// (note on even steps), played as four distinct bars via the seq chain.
// MIDI: A4=69 C5=72 D5=74 E5=76 F5=77
// Bar 1: rest A  C  D  E  A  rest
// Bar 2: rest A  C  D  E  F  E   C
// Bar 3: D  rest rest C rest E  A
// Bar 4: (silent — melody drops out, drums carry the bar)
const ZN_1 = seqFromNotes(
  [null, null, 69, null, 72, null, 74, null, 76, null, 69, null, null, null, 69, null], 0.9, 0.95);
const ZN_2 = seqFromNotes(
  [null, null, 69, null, 72, null, 74, null, 76, null, 77, null, 76, null, 72, null], 0.9, 0.95);
const ZN_3 = seqFromNotes(
  [74, null, null, null, 74, null, 72, null, null, null, 76, null, 69, null, null, null], 0.9, 0.95);
const ZN_4 = seqFromNotes(
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], 0.95, 0.95);
const ZN_DRUM_A = drumFrom({
  0: [0, 4, 8, 12],                       // four-on-the-floor
  7: [4, 12],                             // clap on the backbeat
  2: [0, 4, 8, 12],                       // closed hat on the beat
  3: [2, 6, 10, 14],                      // open hat offbeats
});
const ZN_DRUM_B = drumFrom({
  0: [0, 4, 8, 12], 7: [4, 12],
  2: [0, 2, 4, 6, 8, 10, 12, 14], 3: [2, 6, 10, 14], 1: [15],
});

// --- I Feel Love: hypnotic mono octave-pulse bass through a resonant ladder ---
const IFL_A = seqFromNotes(
  [45, 45, 57, 45, 45, 45, 57, 45, 45, 45, 57, 45, 45, 45, 57, 45], 0.5, 0.9);
const IFL_B = seqFromNotes(
  [45, 45, 57, 45, 48, 48, 60, 48, 52, 52, 64, 52, 50, 50, 62, 50], 0.5, 0.9);
const IFL_DRUM_A = drumFrom({
  0: [0, 4, 8, 12],                       // four-on-the-floor kick
  2: [0, 2, 4, 6, 8, 10, 12, 14],         // driving closed hats
  7: [4, 12],                             // clap backbeat
});
const IFL_DRUM_B = drumFrom({
  0: [0, 4, 8, 12], 2: [0, 2, 4, 6, 8, 10, 12, 14],
  3: [2, 6, 10, 14], 7: [4, 12], 1: [15], // + open-hat offbeats & pickup
});

/**
 * Drop-in demos: any `*.json` SongFile in `./demos` is auto-registered, ordered
 * by filename, and listed *before* the hand-authored built-ins below so
 * dropped-in songs lead the demo button row.
 *
 * **Fetched on click, not bundled** (song-mode.md REQ-11). Eagerly importing
 * them put ~835 kB of JSON — 13 songs — into the boot payload, parsed as JS
 * object literals and held resident, so that the user could load at most one.
 * A `?url` glob keeps only the URLs (a handful of strings); the same treatment
 * `ZIP_DEMOS` below has always had.
 *
 * The trade the `?url` form makes is that the song's own `name` field is no
 * longer readable at build time — which is where `demos-index.json` comes in.
 * It is generated by `scripts/clean-demos.ts` (the pass that already parses
 * every demo) and guarded by `npm run check:demos`, so the button labels stay
 * byte-identical to the names inside the files. Filenames alone would not do:
 * `hacienda_neworder.json` is "Haçienda".
 */
const DEMO_URLS = import.meta.glob<string>('./demos/*.json', {
  eager: true,
  query: '?url',
  import: 'default',
});

export interface DemoRef {
  /** The song's own `name` — what the demo button says. */
  name: string;
  url: string;
}

export const JSON_DEMOS: DemoRef[] = Object.keys(DEMO_URLS)
  .sort()
  .map((path) => {
    const file = path.replace(/^.*\//, '');
    return { name: DEMO_INDEX[file] ?? file.replace(/\.(websynth\.)?json$/i, ''), url: DEMO_URLS[path]! };
  });

const BUILTIN_DEMOS: Record<string, SongFile> = {
  'Zombie Nation': {
    format: 'websynth-song',
    version: 1,
    name: 'Zombie Nation',
    params: {
      ...baseParams(),
      'voicing.mode': 0,            // mono lead
      // Dirty: saw + detuned square, fat unison beating, a little noise,
      // a driven resonant ladder and a distortion stage on top.
      'osc1.wave': 2, 'osc1.octave': 0, 'osc1.level': 0.85,
      'osc2.wave': 3, 'osc2.octave': -1, 'osc2.detune': 12, 'osc2.level': 0.4,
      'unison.voices': 3, 'unison.detune': 24,
      'mixer.noise': 0.06, 'mixer.glide': 0, 'glide.mode': 0,
      'filter.cutoff': 70, 'filter.resonance': 0.6, 'filter.drive': 2.0, 'filter.envAmount': 16,
      'env.amp.attack': 0.004, 'env.amp.decay': 0.15, 'env.amp.sustain': 0.16, 'env.amp.release': 0.14,
      'env.fil.attack': 0.004, 'env.fil.decay': 0.3, 'env.fil.sustain': 0.4, 'env.fil.release': 0.2,
      'fx.dist.on': 1, 'fx.dist.drive': 0.55, 'fx.dist.tone': 3000, 'fx.dist.mix': 0.85,
      'fx.delay.on': 1, 'fx.delay.time': 0.21, 'fx.delay.feedback': 0.3, 'fx.delay.mix': 0.22,
      'fx.reverb.on': 1, 'fx.reverb.size': 0.45, 'fx.reverb.damp': 0.5, 'fx.reverb.mix': 0.12,
      'analog.drift': 0.1,
      'transport.bpm': 130,
    },
    seqBanks: [ZN_1, ZN_2, ZN_3, ZN_4],
    drumBanks: pad4Drum(ZN_DRUM_A, ZN_DRUM_B),
    seqChain: { enabled: true, steps: [0, 1, 2, 3] },   // four distinct bars
    drumChain: { enabled: true, steps: [0, 0, 0, 1] },  // fill on bar 4
    xy: {
      'x': 'osc1.octave',
      'y': 'osc2.octave'
    },
  },

  'I Feel Love': {
    format: 'websynth-song',
    version: 1,
    name: 'I Feel Love',
    params: {
      ...baseParams(),
      'voicing.mode': 0,            // mono
      'glide.mode': 0, 'mixer.glide': 0,            // staccato 16ths
      'osc1.wave': 2, 'osc1.octave': -1, 'osc1.level': 0.85,
      'osc2.wave': 3, 'osc2.octave': -1, 'osc2.detune': -7, 'osc2.level': 0.35,
      'sub.wave': 0, 'sub.octave': -1, 'sub.level': 0.4,
      'filter.cutoff': 60, 'filter.resonance': 1.5, 'filter.drive': 1.8,
      'filter.envAmount': 30,
      'env.amp.attack': 0.002, 'env.amp.decay': 0.16, 'env.amp.sustain': 0.5,
      'env.amp.release': 0.08,
      'env.fil.attack': 0.001, 'env.fil.decay': 0.18, 'env.fil.sustain': 0.15,
      'env.fil.release': 0.1,
      'lfo.rate': 0.5, 'lfo.amount': 0.25, 'lfo.wave': 0, 'lfo.dest': 1,
      'fx.dist.on': 1, 'fx.dist.drive': 0.05, 'fx.dist.tone': 1500, 'fx.dist.mix': 0.35,
      'fx.delay.on': 1, 'fx.delay.time': 0.3, 'fx.delay.feedback': 0.32,
      'fx.delay.mix': 0.18,
      'fx.reverb.on': 1, 'fx.reverb.size': 0.4, 'fx.reverb.damp': 0.5,
      'fx.reverb.mix': 0.14,
      'analog.drift': 0.08,
      'transport.bpm': 125,
      'drum.master': 0.9,
    },
    seqBanks: pad4Seq(IFL_A, IFL_B),
    drumBanks: pad4Drum(IFL_DRUM_A, IFL_DRUM_B),
    seqChain: { enabled: true, steps: [0, 0, 0, 1] },   // A A A B
    drumChain: { enabled: true, steps: [0, 1] },
  },
};

/**
 * The demos that ship *inside the bundle* — the two hand-authored literals.
 * They stay synchronous because callers depend on it: the guided tour applies
 * one mid-step, and `ai-prompt.ts` renders `DEMO_SONGS['I Feel Love']` as its
 * worked example. The 13 drop-ins are `JSON_DEMOS` (fetched on click) and the
 * project bundles are `ZIP_DEMOS`; `SongPanel.loadDemo` dispatches across all
 * three, and `demoNames()` lists them in button order.
 */
export const DEMO_SONGS: Record<string, SongFile> = { ...BUILTIN_DEMOS };

// Project-zip demos (project-export.md REQ-7): any *.websynth.zip dropped into
// ./demos registers as a demo button, fetched lazily on click (a user gesture)
// and applied via the song-panel's project-bundle path — so a demo can ship
// WITH its sampler audio. `?url` keeps the (potentially large) zip out of the
// JS bundle; an empty glob (no assets committed) costs nothing.
// Unlike DEMO_SONGS these are async by nature, so they stay out of
// Song.list()/loadSlot(), which remain sync and JSON-only.
const ZIP_URLS = import.meta.glob<string>('./demos/*.websynth.zip', {
  eager: true,
  query: '?url',
  import: 'default',
});
export const ZIP_DEMOS: DemoRef[] = Object.keys(ZIP_URLS)
  .sort()
  .map((path) => ({
    // Display name: filename minus extension, underscores → spaces — the zip
    // can't be opened at build time, and export filenames underscore-sanitize
    // (projectFilename), so "Run_Away_2" round-trips to "Run Away 2".
    name: path.replace(/^.*\//, '').replace(/\.websynth\.zip$/i, '').replace(/_+/g, ' '),
    url: ZIP_URLS[path]!,
  }));

/**
 * Every demo name, in the order the Song panel's buttons show them: drop-in
 * JSON first, then the built-ins, then the project zips. One source of order so
 * the button row, the tour's fallback and the empty-play modal's random pick
 * cannot disagree about what exists.
 */
export function demoNames(): string[] {
  return [
    ...JSON_DEMOS.map((d) => d.name),
    ...Object.keys(DEMO_SONGS),
    ...ZIP_DEMOS.map((d) => d.name),
  ];
}
