/**
 * A complete song: every synth parameter + all sequencer/drum banks +
 * both chain lanes. Portable as a JSON file and storable in localStorage
 * slots (mirrors the Presets pattern in `preset.ts`).
 */
import type { ParamBus } from './params';
import type { PatternStore, SeqStep, DrumCell, SamplerStep, MotionStep, MotionAssign, MotionTrack } from './patterns';
import { SEQ_LENGTH, DRUM_TRACK_COUNT, makeDrumBank, makeSeqBank, emptyPatternSnapshot } from './patterns';
import type { Arrangement } from '../audio/transport/arrangement';
import type { XyPadStore, XyAssign } from './xy-pad';
import { XY_DEFAULT_ASSIGN } from './xy-pad';
import { validateSongFile } from './song-validate';
import { isAuthorSong, expandAuthorSong } from './song-author';
import { compactSongForExport } from './serialize';
import { SlotStore } from './slot-store';
import { SONG_VERSION } from './song-version';
import { demoMetaOf, type DemoMeta } from './demo-meta';
// Re-exported so the long-standing `import { SONG_VERSION } from './song'` keeps
// working; the constant itself lives in a pure module the MCP bundle can read.
export { SONG_VERSION } from './song-version';
// Generated by `npm run clean:demos`, guarded by `npm run check:demos`. Widened
// from the literal type TS infers for a JSON import — it is looked up by a
// filename computed at runtime, and an entry may legitimately be missing (a demo
// added without regenerating the index; the demo lists fall back to the filename).
// Carries each demo's tempo/length/machines as well as its name — see
// specs/features/demo-library.md.
import demoIndexJson from './demos-index.json';
const DEMO_INDEX = demoIndexJson as Record<string, DemoMeta | undefined>;

const store = new SlotStore('websynth.song.');

/**
 * How every user-facing song/demo name is ordered — the demo row (`demoNames`)
 * and the slot picker (`Song.list`), so the two cannot disagree about where a
 * name sits (song-mode.md REQ-12).
 *
 * `numeric` so the year-named demos read as numbers (1973 · 1979 · 1983 ·
 * 1985-1 · 1985-2) rather than lexically; `sensitivity: 'base'` so an accent
 * files under its base letter and case never splits the list in two.
 */
export const compareSongNames = (a: string, b: string): number =>
  a.localeCompare(b, undefined, { sensitivity: 'base', numeric: true });

export interface ChainData {
  enabled: boolean;
  steps: number[];
}

export interface SongFile {
  format: 'websynth-song';
  /** Hand-maintained alongside `SONG_VERSION` — TS cannot derive `1|…|N` from a
   *  number without recursive-type machinery this codebase doesn't use. */
  version: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  name: string;
  params: Record<string, number>;
  /** v1-v5: one track per bank. Since v6 this is still **track 1** only —
   *  tracks 2-4 live in the additive `seqTracks` (sequencer.md REQ-13). */
  seqBanks: SeqStep[][];
  /**
   * v6 — `seqTracks[bank][track]`, indexed by the REAL track number, so index 0
   * is always null (track 1 is `seqBanks`). An empty track is null. Costs one
   * null per bank and removes the off-by-one an "extra tracks" array invites.
   */
  seqTracks?: (SeqStep[] | null)[][];
  drumBanks: DrumCell[][][];
  seqChain: ChainData;
  drumChain: ChainData;
  // ---- v2: sampler (optional so v1 files still load) ----
  samplerBanks?: SamplerStep[][][];
  samplerChain?: ChainData;
  /** Filenames only — decoded audio is not embedded; user reloads files. */
  sampleNames?: (string | null)[];
  // ---- v3: XY Pad axis assignment (optional so v1/v2 files still load) ----
  xy?: XyAssign;
  // ---- v4: motion sequencer (optional so v1-v3 files still load) ----
  motionBanks?: MotionStep[][];
  /** Per-bank axis override; null = inherit the song's XY Pad assignment. */
  motionAssigns?: (MotionAssign | null)[];
  motionChain?: ChainData;
  /** v5 — the two extra single-param motion tracks per bank. */
  motionTracks?: (MotionTrack | null)[][];
  /**
   * v7 — one semitone offset per `seqChain` slot, parallel to `seqChain.steps`
   * (arrangement.md REQ-8). A **sibling** of `seqChain`, not a field inside it,
   * so `ChainData` keeps its exact shape and every v1-v6 file round-trips
   * byte-identically. Omitted when every offset is 0.
   */
  seqTranspose?: number[];
}

/**
 * The narrow sampler view `apply` needs to evict stale audio (song-mode.md
 * REQ-3b). Structural, so `state/` never imports the audio layer —
 * `SamplerMachine` satisfies it.
 */
export interface SamplerSlots {
  setBuffer(slot: number, buf: AudioBuffer | null): void;
}

/**
 * Split the store's 3-D seq banks into the v6 file shape: track 1 stays in
 * `seqBanks` (handled by the caller) and tracks 2-4 become `seqTracks`, with an
 * empty track written as null. When no extra track holds a step the key is
 * omitted entirely, so a one-track song serializes exactly as it did pre-v6.
 */
function splitSeqTracks(banks: SeqStep[][][]): { seqTracks?: (SeqStep[] | null)[][] } {
  const used = banks.some((bank) => bank.slice(1).some((row) => row.some((s) => s.on)));
  if (!used) return {};
  return {
    seqTracks: banks.map((bank) =>
      bank.map((row, t) => (t === 0 || !row.some((s) => s.on) ? null : row.map((s) => ({ ...s }))))),
  };
}

/** The inverse: rebuild `[bank][track][step]` for the store. Every version
 *  before 6 simply has no `seqTracks`, so its banks come back one-track. */
function mergeSeqTracks(file: SongFile): SeqStep[][][] {
  return file.seqBanks.map((track0, b) => {
    const bank = makeSeqBank();
    bank[0] = track0;
    const extra = file.seqTracks?.[b];
    if (extra) {
      for (let t = 1; t < bank.length; t++) {
        const row = extra[t];
        if (row) bank[t] = row;
      }
    }
    return bank;
  });
}

export const Song = {
  capture(bus: ParamBus, patterns: PatternStore, arr: Arrangement, name: string, xy?: XyPadStore): SongFile {
    const snap = patterns.snapshot();
    return {
      format: 'websynth-song',
      version: SONG_VERSION,
      name,
      params: bus.snapshot(),
      // Track 1 keeps the v1-v5 field; 2-4 ride in the additive one, omitted
      // entirely when empty so a one-track song is byte-identical to before.
      seqBanks: snap.seqBanks.map((bank) => bank[0]!.map((s) => ({ ...s }))),
      ...splitSeqTracks(snap.seqBanks),
      drumBanks: snap.drumBanks,
      seqChain: { enabled: arr.seq.enabled, steps: [...arr.seq.steps] },
      drumChain: { enabled: arr.drum.enabled, steps: [...arr.drum.steps] },
      samplerBanks: snap.samplerBanks,
      samplerChain: { enabled: arr.sampler.enabled, steps: [...arr.sampler.steps] },
      sampleNames: [...patterns.sampleNames],
      xy: xy ? xy.get() : { ...XY_DEFAULT_ASSIGN },
      motionBanks: snap.motionBanks,
      motionAssigns: snap.motionAssigns,
      motionTracks: snap.motionTracks,
      motionChain: { enabled: arr.motion.enabled, steps: [...arr.motion.steps] },
      // v7, and only when it says something: an all-zero array is what every
      // pre-v7 song has, so omitting it keeps those files byte-identical and
      // lets compactSongForExport's version floor stay below 7 (song-mode.md
      // REQ-16). Same trick seqTracks uses.
      ...(arr.seq.transpose.some((t) => t !== 0)
        ? { seqTranspose: [...arr.seq.transpose] }
        : {}),
    };
  },

  apply(
    file: SongFile,
    bus: ParamBus,
    patterns: PatternStore,
    arr: Arrangement,
    xyStore?: XyPadStore,
    sampler?: SamplerSlots,
  ): void {
    bus.resetDefaults();      // authoritative: clear stale params before applying
    bus.restore(file.params);
    // A slot's decoded buffer belongs to the NAME beside it, so evict the audio
    // of every slot this file renames (song-mode.md REQ-3b) — otherwise the
    // previous song's sample keeps playing under the new song's label, with no
    // .needs-reload hint to betray it. Done BEFORE restore so the store's own
    // sample-meta emit repaints each slot against the settled buffers. A file
    // that OMITS sampleNames renames nothing, so the REQ-3 inherit exception
    // below still holds for v1 files.
    if (sampler && file.sampleNames) {
      for (let i = 0; i < patterns.sampleNames.length; i++) {
        if ((file.sampleNames[i] ?? null) !== (patterns.sampleNames[i] ?? null)) {
          sampler.setBuffer(i, null);
        }
      }
    }
    // Motion is authoritative: a file that omits a motion section has it BLANKED,
    // never inherited from the previously-loaded song (song-mode.md REQ-3,
    // motion-sequencer.md "Old songs load unchanged"). Without the `?? blank`
    // fallbacks, restore's skip-on-undefined leaves the prior song's anchors /
    // tracks live and still automating. Sampler banks/names are deliberately left
    // to inherit (see the v1-apply test): a file with no sampler section keeps the
    // user's loaded kit rather than orphaning it.
    const blank = emptyPatternSnapshot();
    patterns.restore({
      seqBanks: mergeSeqTracks(file),
      drumBanks: file.drumBanks,
      samplerBanks: file.samplerBanks,
      sampleNames: file.sampleNames,
      motionBanks: file.motionBanks ?? blank.motionBanks,
      motionAssigns: file.motionAssigns ?? blank.motionAssigns,
      motionTracks: file.motionTracks ?? blank.motionTracks,
    });
    // `?? []` — not "leave it alone": apply() is authoritative (REQ-3), so a file
    // without transposes must clear the last song's, not inherit them. fitTranspose
    // pads to the chain length, so [] means every slot at 0.
    arr.setSeqChain(
      file.seqChain?.steps ?? [0],
      file.seqChain?.enabled ?? false,
      file.seqTranspose ?? [],
    );
    arr.setDrumChain(file.drumChain?.steps ?? [0], file.drumChain?.enabled ?? false);
    arr.setSamplerChain(file.samplerChain?.steps ?? [0], file.samplerChain?.enabled ?? false);
    arr.setMotionChain(file.motionChain?.steps ?? [0], file.motionChain?.enabled ?? false);
    xyStore?.set(file.xy ?? XY_DEFAULT_ASSIGN);
  },

  /**
   * Serialize to the *canonical compact* form: numbers rounded to 4 significant
   * figures and step cells written default-sparse (`compactSongForExport`).
   * `saveSlot`/project zips/share links are whitespace-compact; `download` passes
   * `pretty` (matching `npm run clean:demos` byte-for-byte) so an exported file
   * dropped into `src/state/demos/` keeps readable git diffs.
   * `apply()`/`restore` re-expand the defaults on load — sound is unchanged.
   */
  toJSON(file: SongFile, pretty = false): string {
    return JSON.stringify(compactSongForExport(file), null, pretty ? 2 : undefined);
  },

  fromJSON(text: string): SongFile | null {
    const res = Song.parse(text);
    return res.ok ? res.file : null;
  },

  /** Like `fromJSON` but returns field-level errors instead of collapsing to null. */
  parse(text: string): import('./song-validate').SongValidation {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch (e) {
      return { ok: false, errors: ['File is not valid JSON: ' + (e as Error).message] };
    }
    // The compact authoring dialect expands to a canonical v3 file here, so
    // every ingest surface (Import, launchQueue, project zips, share links,
    // MCP) accepts it automatically. Input-only — see ADR-013.
    //
    // The expand/validate pass is inside a `try` too (untrusted-input.md REQ-2):
    // both walk payload-shaped structures, so a pathological one can still raise
    // a RangeError (stack) or similar. A refused song must look like a failed
    // validation to every caller, never an exception escaping the import path.
    try {
      if (isAuthorSong(parsed)) return expandAuthorSong(parsed);
      return validateSongFile(parsed);
    } catch (e) {
      return { ok: false, errors: ['This file could not be read: ' + (e as Error).message] };
    }
  },

  download(file: SongFile): void {
    const blob = new Blob([Song.toJSON(file, true) + '\n'], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${file.name.replace(/[^a-z0-9_-]+/gi, '_') || 'song'}.websynth.json`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  },

  readFile(f: File): Promise<SongFile | null> {
    return f.text().then((t) => Song.fromJSON(t));
  },

  /** Like `readFile` but returns field-level validation errors for the import UI. */
  parseFile(f: File): Promise<import('./song-validate').SongValidation> {
    return f.text().then((t) => Song.parse(t));
  },

  // ---- localStorage slots ----

  /**
   * Slot-picker contents: every JSON demo name (drop-in and built-in) plus the
   * user's stored slots, deduped and sorted. Drop-ins are listed even though
   * `loadSlot` cannot return them — they are fetched, not bundled (REQ-12) — so
   * the Song panel's Load button falls back to `loadDemo` for a name with no
   * stored slot. Zip demos stay out, as they always have: they are project
   * bundles, not song files.
   */
  list(): string[] {
    return [...new Set([
      ...JSON_DEMOS.map((d) => d.name),
      ...Object.keys(DEMO_SONGS),
      ...store.readIndex(),
    ])].sort(compareSongNames);
  },

  saveSlot(name: string, file: SongFile): void {
    store.writeRaw(name, Song.toJSON(file));
    store.addToIndex(name);
  },

  /**
   * Is there a **stored** slot under this name — i.e. would `saveSlot` destroy
   * something the user made? Deliberately not `list()`, which also reports demos
   * (nothing of the user's is lost by overwriting a demo name).
   */
  hasSlot(name: string): boolean {
    return store.readRaw(name) !== null;
  },

  /**
   * Is there a stored slot under this song's name holding something **else**?
   * The one test behind every "may I overwrite?" dialog (session-autosave.md
   * REQ-14b/14c) — no slot, or a slot already holding these exact bytes, is
   * false: there is nothing to lose, so there is nothing to ask.
   *
   * A name match alone is NOT the question. When the slot holds the exact bytes
   * the save would write, the write is a no-op, so re-opening the same share
   * link — or re-saving a song you have not touched — must not ask: a prompt
   * that returns however you answer it is one the user stops reading. Hence the
   * comparison against `saveSlot`'s own serialization: canonical and compact
   * (ADR-011), so equal songs give equal strings, and any encoding difference
   * errs toward asking.
   */
  slotDiffers(file: SongFile): boolean {
    const raw = store.readRaw(file.name);
    return raw !== null && raw !== Song.toJSON(file);
  },

  /**
   * Would writing this song to its slot destroy work the user would miss?
   * (session-autosave.md REQ-14/14b/14c.)
   *
   * A *plan*, not an action — the same idiom as `preset-file.ts` `planImport`:
   * the decision is pure and testable here, and the UI owns the dialog.
   *
   * `from` is the slot the current session came from, if any. Saving a song back
   * to the slot it came from is the normal edit loop and must stay one click;
   * every other write lands on music the user has not been working on, so it
   * asks. An import has no provenance at all — hence `planImportSave`.
   */
  planSlotSave(file: SongFile, from: string | null): { name: string; conflict: boolean } {
    return { name: file.name, conflict: file.name !== from && Song.slotDiffers(file) };
  },

  /**
   * `planSlotSave` for an import, which never has provenance: nothing about an
   * arriving file makes its name *yours* (session-autosave.md REQ-14,
   * untrusted-input.md REQ-9). The name comes from the file, so with a share
   * link it is attacker-chosen: a song called "My Song" would otherwise destroy
   * that slot at boot, and the load-undo toast cannot bring it back — it
   * restores the in-memory session, not localStorage.
   */
  planImportSave(file: SongFile): { name: string; conflict: boolean } {
    return Song.planSlotSave(file, null);
  },

  /**
   * A stored slot, else a **built-in** demo. Stays synchronous and JSON-only, so
   * the fetched demos (drop-in JSON and zip alike) are not reachable here —
   * `SongPanel.loadDemo` is the door that knows about all three (REQ-12).
   */
  loadSlot(name: string): SongFile | null {
    const raw = store.readRaw(name);
    if (raw) return Song.fromJSON(raw);
    return DEMO_SONGS[name] ?? null;
  },

  deleteSlot(name: string): void {
    store.remove(name);
  },
};

/* ---------------- Demo songs ---------------- */

function baseParams(): Record<string, number> {
  const p: Record<string, number> = {
    'voicing.mode': 1,
    'osc1.wave': 2, 'osc1.octave': 0, 'osc1.detune': 0, 'osc1.level': 0.7,
    'osc2.wave': 2, 'osc2.octave': 0, 'osc2.detune': 7, 'osc2.level': 0.5,
    'sub.wave': 0, 'sub.octave': -1, 'sub.level': 0,
    'unison.voices': 1, 'unison.detune': 12,
    'analog.drift': 0,
    'mixer.noise': 0, 'mixer.glide': 0, 'glide.mode': 1,
    'filter.cutoff': 90, 'filter.resonance': 0.5, 'filter.drive': 1.2, 'filter.envAmount': 24,
    'env.amp.attack': 0.005, 'env.amp.decay': 0.2, 'env.amp.sustain': 0.8, 'env.amp.release': 0.4,
    'env.fil.attack': 0.005, 'env.fil.decay': 0.6, 'env.fil.sustain': 0.2, 'env.fil.release': 0.4,
    'lfo.rate': 4, 'lfo.amount': 0, 'lfo.wave': 0, 'lfo.dest': 0,
    'fx.dist.on': 0, 'fx.dist.drive': 0.3, 'fx.dist.tone': 3000, 'fx.dist.mix': 1,
    'fx.wah.on': 0, 'fx.phaser.on': 0,
    'fx.delay.on': 0, 'fx.delay.time': 0.35, 'fx.delay.feedback': 0.4, 'fx.delay.mix': 0.3,
    'fx.reverb.on': 0, 'fx.reverb.size': 0.6, 'fx.reverb.damp': 0.4, 'fx.reverb.mix': 0.25,
    'fx.djfilter': 0,
    'master.volume': 0.8, 'master.pitchBend': 0, 'master.modWheel': 0,
    'transport.bpm': 120,
    'arp.on': 0, 'seq.on': 1, 'drum.on': 1, 'drum.master': 0.9,
  };
  for (let i = 0; i < DRUM_TRACK_COUNT; i++) {
    p[`drum.t${i}.vol`] = 0.85;
    p[`drum.t${i}.tune`] = 0;
    p[`drum.t${i}.decay`] = 0.3;
    p[`drum.t${i}.mute`] = 0;
  }
  return p;
}

// NOTE: the seq helpers below deliberately do NOT share PatternStore's
// makeSeqBank() — they use different constants (fixed note 60, velocity 0.85 vs
// 60 + i%8 / 0.8), and those values are serialized into the committed demo
// songs and into share-link payloads. Unifying them would change demo bytes.
function seqFromNotes(notes: (number | null)[], gate = 0.5, velocity = 0.85): SeqStep[] {
  return Array.from({ length: SEQ_LENGTH }, (_, i) => {
    const n = notes[i] ?? null;
    return { on: n !== null, note: n ?? 60, velocity, gate, prob: 1, ratchet: 1, tie: false, micro: 0 };
  });
}

function emptySeq(): SeqStep[] {
  return seqFromNotes(Array(SEQ_LENGTH).fill(null));
}

/** rows: map of track index → array of step indices that are ON. */
function drumFrom(rows: Record<number, number[]>): DrumCell[][] {
  const bank = makeDrumBank();
  for (const [t, steps] of Object.entries(rows)) {
    for (const s of steps) {
      const cell = bank[Number(t)]?.[s];
      if (cell) cell.on = true;
    }
  }
  return bank;
}

function pad4Seq(a: SeqStep[], b: SeqStep[]): SeqStep[][] {
  return [a, b, a.map((s) => ({ ...s })), a.map((s) => ({ ...s }))];
}
function pad4Drum(a: DrumCell[][], b: DrumCell[][]): DrumCell[][][] {
  const copy = (g: DrumCell[][]) => g.map((r) => r.map((c) => ({ ...c })));
  return [a, b, copy(a), copy(a)];
}

// --- Mordor: hypnotic mono octave-pulse bass through a resonant ladder ---
const MOR_A = seqFromNotes(
  [45, 45, 57, 45, 45, 45, 57, 45, 45, 45, 57, 45, 45, 45, 57, 45], 0.5, 0.9);
const MOR_B = seqFromNotes(
  [45, 45, 57, 45, 48, 48, 60, 48, 52, 52, 64, 52, 50, 50, 62, 50], 0.5, 0.9);
const MOR_DRUM_A = drumFrom({
  0: [0, 4, 8, 12],                       // four-on-the-floor kick
  2: [0, 2, 4, 6, 8, 10, 12, 14],         // driving closed hats
  7: [4, 12],                             // clap backbeat
});
const MOR_DRUM_B = drumFrom({
  0: [0, 4, 8, 12], 2: [0, 2, 4, 6, 8, 10, 12, 14],
  3: [2, 6, 10, 14], 7: [4, 12], 1: [15], // + open-hat offbeats & pickup
});

/**
 * Drop-in demos: any `*.json` SongFile in `./demos` is auto-registered, ordered
 * by filename, and listed *before* the hand-authored built-in below so
 * dropped-in songs lead the demo button row.
 *
 * **Fetched on click, not bundled** (song-mode.md REQ-11). Eagerly importing
 * them put the whole library — hundreds of kB of JSON — into the boot payload,
 * parsed as JS object literals and held resident, so the user could load one.
 * A `?url` glob keeps only the URLs (a handful of strings); the same treatment
 * `ZIP_DEMOS` below has always had.
 *
 * The trade the `?url` form makes is that the song's own `name` field is no
 * longer readable at build time — which is where `demos-index.json` comes in.
 * It is generated by `scripts/clean-demos.ts` (the pass that already parses
 * every demo) and guarded by `npm run check:demos`, so the button labels stay
 * byte-identical to the names inside the files. Filenames alone would not do:
 * `hacienda_neworder.json` is "Haçienda".
 */
const DEMO_URLS = import.meta.glob<string>('./demos/*.json', {
  eager: true,
  query: '?url',
  import: 'default',
});

export interface DemoRef {
  /** The song's own `name` — what the demo button says. */
  name: string;
  url: string;
  /** Generated facts + any hand-written blurb; absent for an unindexed demo. */
  meta?: DemoMeta;
}

export const JSON_DEMOS: DemoRef[] = Object.keys(DEMO_URLS)
  .sort()
  .map((path) => {
    const file = path.replace(/^.*\//, '');
    const meta = DEMO_INDEX[file];
    const ref: DemoRef = {
      name: meta?.name ?? file.replace(/\.(websynth\.)?json$/i, ''),
      url: DEMO_URLS[path]!,
    };
    if (meta) ref.meta = meta;
    return ref;
  });

const BUILTIN_DEMOS: Record<string, SongFile> = {
  'Mordor': {
    format: 'websynth-song',
    version: 1,
    name: 'Mordor',
    params: {
      ...baseParams(),
      'voicing.mode': 0,            // mono
      'glide.mode': 0, 'mixer.glide': 0,            // staccato 16ths
      'osc1.wave': 2, 'osc1.octave': -1, 'osc1.level': 0.85,
      'osc2.wave': 3, 'osc2.octave': -1, 'osc2.detune': -7, 'osc2.level': 0.35,
      'sub.wave': 0, 'sub.octave': -1, 'sub.level': 0.4,
      'filter.cutoff': 60, 'filter.resonance': 1.5, 'filter.drive': 1.8,
      'filter.envAmount': 30,
      'env.amp.attack': 0.002, 'env.amp.decay': 0.16, 'env.amp.sustain': 0.5,
      'env.amp.release': 0.08,
      'env.fil.attack': 0.001, 'env.fil.decay': 0.18, 'env.fil.sustain': 0.15,
      'env.fil.release': 0.1,
      'lfo.rate': 0.5, 'lfo.amount': 0.25, 'lfo.wave': 0, 'lfo.dest': 1,
      'fx.dist.on': 1, 'fx.dist.drive': 0.05, 'fx.dist.tone': 1500, 'fx.dist.mix': 0.35,
      'fx.delay.on': 1, 'fx.delay.time': 0.3, 'fx.delay.feedback': 0.32,
      'fx.delay.mix': 0.18,
      'fx.drum.comp.on': 1,
      'fx.reverb.on': 1, 'fx.reverb.size': 0.4, 'fx.reverb.damp': 0.5,
      'fx.reverb.mix': 0.14,
      'analog.drift': 0.08,
      'transport.bpm': 125,
      'drum.master': 0.9,
    },
    seqBanks: pad4Seq(MOR_A, MOR_B),
    drumBanks: pad4Drum(MOR_DRUM_A, MOR_DRUM_B),
    seqChain: { enabled: true, steps: [0, 0, 0, 1] },   // A A A B
    drumChain: { enabled: true, steps: [0, 1] },
  },
};

/**
 * The demo that ships *inside the bundle* — the one hand-authored literal.
 * It stays synchronous because callers depend on that: `Song.loadSlot` falls
 * back to it, and `ai-prompt.ts` renders `DEMO_SONGS['Mordor']` as its
 * worked example. The drop-ins are `JSON_DEMOS` (fetched on click) and the
 * project bundles are `ZIP_DEMOS`; `SongPanel.loadDemo` dispatches across all
 * three, and `demoNames()` lists them in button order.
 */
export const DEMO_SONGS: Record<string, SongFile> = { ...BUILTIN_DEMOS };

// Project-zip demos (project-export.md REQ-7): any *.websynth.zip dropped into
// ./demos registers as a demo button, fetched lazily on click (a user gesture)
// and applied via the song-panel's project-bundle path — so a demo can ship
// WITH its sampler audio. `?url` keeps the (potentially large) zip out of the
// JS bundle; an empty glob (no assets committed) costs nothing.
// Unlike DEMO_SONGS these are async by nature, so they stay out of
// Song.list()/loadSlot(), which remain sync and JSON-only.
const ZIP_URLS = import.meta.glob<string>('./demos/*.websynth.zip', {
  eager: true,
  query: '?url',
  import: 'default',
});
export const ZIP_DEMOS: DemoRef[] = Object.keys(ZIP_URLS)
  .sort()
  .map((path) => {
    const file = path.replace(/^.*\//, '');
    // The index now covers zips too (demo-library.md REQ-3) — the generator
    // opens them in Node. The fallback stays: filename minus extension,
    // underscores → spaces, since export filenames underscore-sanitize
    // (projectFilename), so "Run_Away_2" round-trips to "Run Away 2".
    const meta = DEMO_INDEX[file];
    const ref: DemoRef = {
      name: meta?.name ?? file.replace(/\.websynth\.zip$/i, '').replace(/_+/g, ' '),
      url: ZIP_URLS[path]!,
    };
    if (meta) ref.meta = meta;
    return ref;
  });

/**
 * Every demo name, in the order the Song panel's buttons show them: **one
 * alphabetical list by display name**, across all three sources. One source of
 * order so the button row, the tour's fallback and the empty-play modal's random
 * pick cannot disagree about what exists.
 *
 * Which source a demo comes from is a loading detail (song-mode.md REQ-12), and
 * it used to leak into the shelf: the list was the three sources concatenated,
 * each sorted by *filename*. So the project zips always sat last — `1973`, the
 * most feature-complete demo in the library, was pushed past DEMO_ROW_LIMIT into
 * the "All Demos" fold purely for being a `.zip` — and a label that differs from
 * its filename was mis-filed ("Haçienda" under `h`, "Apex Twin" after "Tosti").
 */
export function demoNames(): string[] {
  return [
    ...JSON_DEMOS.map((d) => d.name),
    ...Object.keys(DEMO_SONGS),
    ...ZIP_DEMOS.map((d) => d.name),
  ].sort(compareSongNames);
}

/**
 * What the shelf knows about a demo (demo-library.md REQ-6), or `null` for a
 * name no source owns.
 *
 * The drop-ins and zips read it straight out of the generated index — they are
 * fetched on click, so nothing else can know their tempo before then. The
 * **built-in** is a TS literal already in memory, so its facts are derived on
 * the spot instead; it happens once per button, which is cheaper than teaching
 * the generator about a source it cannot see.
 */
export function demoMetaFor(name: string): DemoMeta | null {
  const ref = JSON_DEMOS.find((d) => d.name === name) ?? ZIP_DEMOS.find((d) => d.name === name);
  if (ref?.meta) return ref.meta;
  const builtin = DEMO_SONGS[name];
  return builtin ? demoMetaOf(builtin) : null;
}

/**
 * Does any of the three sources own this exact name? No fallback — for the one
 * caller that must stay strict (song-mode.md REQ-12).
 */
export function isDemoName(name: string): boolean {
  return name in DEMO_SONGS
    || JSON_DEMOS.some((d) => d.name === name)
    || ZIP_DEMOS.some((d) => d.name === name);
}

/**
 * The demo a name refers to: itself when a source owns it, otherwise the **first
 * demo in button order** (song-mode.md REQ-12, v18).
 *
 * Demo names are data — `src/state/demos/` is a drop-in directory, so renaming or
 * deleting a file is a legitimate change that touches no code. Callers name one
 * anyway: the tour applies `DEMO_FOR_TOUR` by string constant. `loadDemo` used to
 * return silently for an unowned name, which turned a renamed demo into a tour
 * step that loads nothing and a following step that narrates silence. Falling
 * back to a real song keeps every such caller honest.
 *
 * `undefined` only when there are no demos at all.
 */
export function resolveDemoName(name: string): string | undefined {
  return isDemoName(name) ? name : demoNames()[0];
}
