/**
 * Generator for the published parameter reference. Run: `npm run gen:params`.
 *
 * Writes `public/params.json` (the structured catalogue, `buildParamCatalog`)
 * and `public/params.md` (the prose table, rendered by the same `paramTable()`
 * the ✨ AI Prompt and the MCP guides use). Both are built from a fresh
 * `ParamBus` + `registerDefaults()`, so they cannot drift from the registry —
 * and because they live in `public/` they ship in `dist/` and are fetchable
 * from the deployed site, which is the whole point: an agent that can neither
 * open the app nor run the MCP server previously had no parameter list at all
 * (see specs/features/param-catalogue.md).
 *
 * With `GEN_PARAMS_CHECK` set (injected by `scripts/check-params.config.ts`,
 * `npm run check:params`) it writes nothing and instead fails listing every file
 * that isn't byte-identical to its generated form — the CI drift gate, so a
 * parameter added without regenerating cannot ship.
 *
 * It is a vitest entry (driven by `scripts/gen-params.config.ts`, NOT part of
 * `npm test`, which only globs `tests/**`) because vitest is the only Vite-aware
 * TS runner in the toolchain — plain Node cannot resolve the codebase's
 * extensionless relative imports. Same arrangement as `scripts/clean-demos.ts`.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { expect, test } from 'vitest';
import { ParamBus, registerDefaults } from '../src/state/params';
import { buildParamCatalog } from '../src/state/param-catalog';
import { paramTable } from '../src/state/authoring-guide';
import { isPatchParam } from '../src/state/preset-session';

const checkOnly = !!process.env['GEN_PARAMS_CHECK'];

/** The prose reference. Sections mirror the preset/song split (`isPatchParam`). */
function buildParamsMarkdown(bus: ParamBus): string {
  return `<!-- GENERATED by \`npm run gen:params\` from src/state/params.ts — do not edit by hand. -->

# VAST G1-J8 — parameter reference

Every parameter the synth registers, with its range, default and — for a choice
parameter — its value map. The stored value of a choice parameter is the
**index** into that map. Values outside a range are clamped on load.

A **preset** (\`websynth-preset\`) carries the sound parameters below; a **song**
(\`websynth-song\`) carries those *plus* the song-level ones. Both use a sparse
map of \`"<id>": number\`, so you only set what matters.

\`filter.cutoff\` is a MIDI note number, **not** Hz — keep modulation additive in
semitone space.

Machine-readable: [\`params.json\`](params.json) — the same list, plus each
parameter's \`taper\`, \`curve\` and \`unit\`. File formats, versions and JSON
Schemas: [\`llms.txt\`](llms.txt).

## Sound parameters (what a preset carries)

${paramTable(bus, isPatchParam)}

## Song-only parameters (transport, arpeggiator, sequencer, drums, sampler)

${paramTable(bus, (id) => !isPatchParam(id))}
`;
}

test(checkOnly ? 'published parameter reference is current' : 'generate the parameter reference', () => {
  const bus = new ParamBus();
  registerDefaults(bus);

  const publicDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'public');
  const drifted: string[] = [];

  const files: Record<string, string> = {
    'params.json': JSON.stringify(buildParamCatalog(bus), null, 2) + '\n',
    'params.md': buildParamsMarkdown(bus),
  };

  for (const [name, next] of Object.entries(files)) {
    const path = join(publicDir, name);
    // CRLF-normalize before comparing: a Windows working copy may carry CRLF,
    // and that alone is not drift (same guard as scripts/clean-demos.ts).
    const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : '';
    if (next === current) continue;
    if (checkOnly) {
      drifted.push(name);
    } else {
      writeFileSync(path, next);
      // eslint-disable-next-line no-console
      console.log(`wrote public/${name} (${next.length} bytes)`);
    }
  }

  expect(drifted, 'stale parameter reference — run `npm run gen:params`').toEqual([]);
});
